version: "3.3"

services:
  applib:
    image: 'libraryutilization:latest'
    container_name: applib
    depends_on:
      - dblib
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dblib:5432/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - '8080:8181'
  dblib:
    image: postgres
    container_name: dblib
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - '5432:5432'